#!/usr/bin/env python3
"""Derive this project's Codex MCP and Stop configuration from Claude's files.

Run with --check to detect stale generated files without writing them.
Only the two generated files are owned here; keep other Codex settings in the
user configuration. The Stop hook runs without Claude's edit-marker protocol.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generated(root: Path) -> dict[str, str]:
    servers = json.loads((root / '.mcp.json').read_text())['mcpServers']
    lines = ['# Generated by .codex/__sync__.py; edit .mcp.json instead.']
    for name, server in servers.items():
        if server.get('type', 'stdio') != 'stdio':
            raise ValueError(f'Unsupported MCP transport: {name}')
        unknown = set(server) - {'type', 'command', 'args', 'env'}
        if unknown:
            raise ValueError(f'Unsupported MCP fields for {name}: {sorted(unknown)}')
        lines.extend(['', f'[mcp_servers.{json.dumps(name)}]',
                      f'command = {json.dumps(server["command"])}',
                      f'args = {json.dumps(server.get("args", []))}'])
        if server.get('env'):
            lines.extend(['', f'[mcp_servers.{json.dumps(name)}.env]'])
            lines.extend(f'{json.dumps(k)} = {json.dumps(v)}'
                         for k, v in server['env'].items())
    settings = json.loads((root / '.claude/settings.json').read_text())
    groups = settings['hooks']['Stop']
    for group in groups:
        for hook in group['hooks']:
            command = hook['command']
            if hook['type'] != 'command' or not command.endswith('/.claude/hooks/__lean_check__.py"'):
                raise ValueError('Review the changed Stop hook before translating it')
            hook['command'] = command.replace('$CLAUDE_PROJECT_DIR', '$(git rev-parse --show-toplevel)') + ' --always'
    return {'config.toml': '\n'.join(lines) + '\n',
            'hooks.json': json.dumps({'description': 'Generated by .codex/__sync__.py; edit .claude/settings.json instead.',
                                      'hooks': {'Stop': groups}}, indent=2) + '\n'}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for name, text in generated(ROOT).items():
        path = ROOT / '.codex' / name
        if not path.exists() or path.read_text() != text:
            stale.append(name)
            if not args.check:
                path.write_text(text)
    if args.check and stale:
        print('Stale Codex configuration: ' + ', '.join(stale))
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
