name = "MassFormula"
version = "0.1.0"
description = "Serre's mass formula for the totally ramified extensions of given degree of a local field"
keywords = ["math", "number-theory", "local-fields", "ramification"]
homepage = "https://github.com/0stellensatz/MassFormula"
license = "Apache-2.0"
defaultTargets = ["MassFormula"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[require]]
name = "LeanPrism"
git = "https://codeberg.org/wvhulle/lean-prism.git"
rev = "main"

[[lean_lib]]
name = "MassFormula"
